In [1]:
import torch

In [2]:
import numpy as np

In [4]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
x = torch.rand(3,5)
x

tensor([[0.4108, 0.7379, 0.0096, 0.9183, 0.2242],
        [0.7264, 0.1341, 0.7340, 0.2550, 0.3723],
        [0.3053, 0.9230, 0.4470, 0.7635, 0.2835]])

In [19]:
x.stride()

(5, 1)

In [26]:
torch.manual_seed(1)

In [27]:
x = torch.empty(3,5)

In [28]:
x


tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38, 1.0102e-38, 9.9184e-39]])

In [29]:
y = torch.empty(3,5)

In [30]:
y

tensor([[9.2755e-39, 1.0561e-38, 1.0469e-38, 9.5510e-39, 9.9184e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [31]:
z = torch.FloatTensor(3,5)

In [32]:
z

tensor([[9.2755e-39, 1.0561e-38, 1.0469e-38, 9.5510e-39, 9.9184e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39]])